package com.skipissue.maxway.domain.entity.responses

data class ProductsDetailResponse(
    val active: Boolean,
    val active_in_menu: Boolean,
    val add_to_order: Boolean,
    val brand: Brand,
    val categories: List<CategoryX>,
    val code: String,
    val count: String,
    val currency: String,
    val default_quantity: Int,
    val description: Description,
    val favorites: Any,
    val from_time: String,
    val gallery: List<Any>,
    val has_modifier: Boolean,
    val id: String,
    val iiko_id: String,
    val image: String,
    val in_price: Int,
    val is_divisible: Boolean,
    val jowi_id: String,
    val off_always: Boolean,
    val order: String,
    val out_price: Int,
    val product_property: List<Any>,
    val properties: List<Any>,
    val rate: Rate,
    val slug: String,
    val tags: List<Any>,
    val title: TitleX,
    val to_time: String,
    val type: String,
    val variant_products: List<Any>
)